{
 "title": "b1_b2_all_sensor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "1um 먼지농도",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT timestamp, sensor_id, val_0_1um from test_db.lpm_data;"
    }
   ]
  },
  {
   "title": "3um 먼지농도",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT timestamp, sensor_id, val_0_3um from test_db.lpm_data;"
    }
   ]
  },
  {
   "title": "5um 먼지농도",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT timestamp, sensor_id, val_0_5um from test_db.lpm_data;"
    }
   ]
  },
  {
   "title": "wind_data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT sensor_id , timestamp, val from test_db.wind_data;"
    }
   ]
  },
  {
   "title": "temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT val, timestamp, sensor_id from test_db.temp_data;"
    }
   ]
  },
  {
   "title": "esd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT val,timestamp,sensor_id FROM test_db.esd_data;"
    }
   ]
  },
  {
   "title": "hum_data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT val, timestamp, sensor_id from test_db.hum_data;"
    }
   ]
  }
 ]
}